spring:
  mail:
    # 163\u90AE\u7BB1\u7684\u5730\u5740\u4E3Asmtp.163.com\uFF0C\u76F4\u63A5\u586B\u5199\u5373\u53EF
    # qq\u7684\uFF1Asmtp.qq.com
    host: smtp.163.com
    # \u4F60\u7533\u8BF7\u7684163\u90AE\u7BB1
    username: tjut_do_m@163.com
    # \u6CE8\u610F\u5BC6\u7801\u662F\u5728\u5F00\u542Fsmtp/pop3\u65F6\u81EA\u52A8\u751F\u6210\u7684\uFF0C\u8BB0\u5F97\u4FDD\u5B58\u4E00\u4E0B\uFF0C\u4E0D\u7136\u5C31\u627E\u4E0D\u5230\u4E86
    password: HRCFJAHBLPWOPWYN
  datasource:
    url: jdbc:mysql://localhost:3306/depart
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
#  mvc:
#    static-path-pattern: /static/**
  jpa:
    #开启SQL语句执行日志信息
    show-sql: true
    hibernate:
      #第一次配置为create自动创建表，后续应该设置为自动更新表update
      ddl-auto: update