spring:
  mail:
    host: smtp.163.com
    username: tjut_do_m@163.com
    password: HRCFJAHBLPWOPWYN
  datasource:
    url: jdbc:mysql://localhost:3306/depart
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update