spring:
  mail:
    host: smtp.163.com
    username: tjut_do_m@163.com
    password: HRCFJAHBLPWOPWYN
  datasource:
    url: jdbc:mysql://localhost:3306/depart
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: test
    password: glxy
  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update
springfox:
  documentation:
    enabled: false